### ISSUE TITLE
Will I be able to use SPI 

### ISSUE THREAD

**Issue by prasaanth-selvakumar** [Nikolay-Kha/android-things-ws2812b#1]
i just wanted to know if i would be able to use the SPI communication if i connect the neo pixel in MOSI line

**Comment by prasaanth-selvakumar** [comment]
It works fine for three Consecutive Animations then it freezes, it Throws an error Message SPI write not permitted

**Comment by prasaanth-selvakumar** [comment]
03-06 07:47:07.709 640-770/com.example.acer.neo_pixel W/ws2812b: Failed to write to SPI device
                                                                 com.google.android.things.pio.PioException: android.os.ServiceSpecificException: Operation not permitted (code 1)
                                                                     at com.google.android.things.pio.SpiDeviceImpl.transfer(SpiDeviceImpl.java:130)
                                                                     at com.google.android.things.pio.SpiDevice.write(SpiDevice.java:136)
                                                                     at com.example.acer.neo_pixel.WS2812B.commit(WS2812B.java:92)
                                                                     at com.example.acer.neo_pixel.MainActivity$1.run(MainActivity.java:60)
                                                                     at java.util.TimerThread.mainLoop(Timer.java:555)
                                                                     at java.util.TimerThread.run(Timer.java:505)
                                                                  Caused by: android.os.ServiceSpecificException: Operation not permitted (code 1)
                                                                     at android.os.Parcel.readException(Parcel.java:2018)
                                                                     at android.os.Parcel.readException(Parcel.java:1950)
                                                                     at com.google.android.things.pio.IPeripheralManagerClient$Stub$Proxy.SpiDeviceTransfer(IPeripheralManagerClient.java:1094)
                                                                     at com.google.android.things.pio.SpiDeviceImpl.transfer(SpiDeviceImpl.java:128)
                                                                     at com.google.android.things.pio.SpiDevice.write(SpiDevice.java:136) 
                                                                     at com.example.acer.neo_pixel.WS2812B.commit(WS2812B.java:92) 
                                                                     at com.example.acer.neo_pixel.MainActivity$1.run(MainActivity.java:60) 
                                                                     at java.util.TimerThread.mainLoop(Timer.java:555) 
                                                                     at java.util.TimerThread.run(Timer.java:505)
